language: node_js

cache:
  directories:
    - node_modules

before_install:
  - npm cache verify
  - npm prune
  - npm update

node_js:
 - "7"
 - "8"
 - "9"
 - "stable"
before_script:
  - chmod 0777 ./node_modules/.bin/jasmine
  - npm install
script:
  - npm run oneTimeTest
